import Head from 'next/head'
import Image from 'next/image'
import Layout from '@/components/Layout/Layout'
import { useAccount, useProvider, useSigner } from 'wagmi'
import { Text } from '@chakra-ui/react'
import {
  Alert,
  AlertIcon,
  AlertTitle,
  AlertDescription,
} from '@chakra-ui/react'
import { useEffect, useState } from "react";
import Link from 'next/link';
import { useRouter } from 'next/router';
import Auth from './Auth'
import { useAuth } from '@/contexts/authContext';



export default function Home() {
  const router = useRouter();
  const [player, setPlayer] = useState(null);
  const [pvp, setPvp] = useState(null);
  const [game, setGame] = useState(null);
  const [deck, setDeck] = useState([]);
  const [elites, setElites] = useState([]);
  const [showAlert, setShowAlert] = useState(false);
  const { authToken } = useAuth();
  const { address, isConnected } = useAccount()

  async function getPlayer() {
    const response = await fetch(`${`http://localhost:3000/api/v1/find?token=${authToken}`}`);
    return response.json();
  }

  async function getGame() {
    const response = await fetch(`${`http://localhost:3000/api/v1/find_game?token=${authToken}`}`);
    return response.json();
  }

  async function getPvp() {
    const response = await fetch(`${`http://localhost:3000/api/v1/find_pvp?token=${authToken}`}`);
    return response.json();
}

  async function getDeck() {
    const response = await fetch(`${`http://localhost:3000/api/v1/deck?token=${authToken}`}`);
    return response.json();
  }

  async function getElites() {
    const response = await fetch(`${`http://localhost:3000/api/v1/elites?token=${authToken}`}`);
    return response.json();
  }

  async function createPvp() {

    const response = await fetch(`${`http://localhost:3000/api/v1/pvps?token=${authToken}`}`,
      {
        method: "POST",
        headers: {
          "Content-Type": "application/json",
        },
      }
    );
    if (response.ok) {
      const responseData = await response.json();
      if (responseData.id) {
        const pvpId = responseData.id;
        router.push(`/pvp/${pvpId}`)
      }
      setPlayer(responseData.player)
    }
  }

  async function stopPvp() {

    const response = await fetch(`${`http://localhost:3000/api/v1/stop_pvp?token=${authToken}`}`,
      {
        method: "POST",
        headers: {
          "Content-Type": "application/json",
        },
      }
    );
    if (response.ok) {
      const responseData = await response.json();
      setPlayer(responseData.player)
    }
  }

  const redirectZones = () => {
    if (deck.length == 4) {
      window.location.href = "/game/Zones";
    } else {
      alert("You need a team with 5 members");
    }
  };

  useEffect(() => {

    const fetchCurrentPlayer = async () => {
      try {
        const json = await getPlayer();
        setPlayer(json);
      } catch (error) {
        console.error("Failed to fetch the player: ", error);
      }
    };
    fetchCurrentPlayer();
  }, [address, authToken]);

  useEffect(() => {
    const fetchCurrentGame = async () => {
      try {
        const json = await getGame();
        setGame(json);
      } catch (error) {
        setGame(null);
        console.error("Failed to fetch the game: ", error);
      }
    };

    if (player) {
      fetchCurrentGame();
    }
  }, [address, authToken, isConnected, player]);

  useEffect(() => {
    const fetchDeck = async () => {
      try {
        const json = await getDeck();
        setDeck(json);
      } catch (error) {
        console.error("Failed to fetch the player: ", error);
      }
    };
    if (player) {
      fetchDeck();
    }
  }, [player]);

  useEffect(() => {
    const fetchCurrentPvp = async () => {
      try {
        setPvp(player.in_pvp);
      } catch (error) {
        setPvp(null);
        console.error("Failed to fetch the game: ", error);
      }
    };

    if (player) {
      fetchCurrentPvp();
    }
  }, [player]);

  useEffect(() => {
    const fetchCurrentElites = async () => {
      try {
        const json = await getElites();
        setElites(json);
      } catch (error) {
        setElites(null);
        console.error("Failed to fetch the player: ", error);
      }
    };
    if (player) {
      fetchCurrentElites();
    }
  }, [player]);

  return (
    <>
      <Head>
        <title>DApp : Home</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <Layout pvp={pvp}>
        {player ? (
          <div className="App">
            <div>
              {player ? (
                <>
                  <h2>Name: {player.name}</h2>
                  <h2>Energy: {player.energy}</h2>
                  <h2>Monsters: {player.monsters.length}</h2>

                  <Link href="/player/[id]" as={`/player/${player.id}`}>
                    <button style={{
                      color: "#F9DC5C",
                      backgroundColor: "blue",
                      padding: "10px 50px",
                      margin: 10,
                      transition: "background-color 0.3s ease",
                      borderRadius: 5,
                      textDecoration: "none"
                    }} >Deck </button>
                  </Link>
                  {game && deck ? (
                    <Link href="/game/[id]" as={`/game/${game.id}`}>
                      <button style={{
                        color: "#F9DC5C",
                        backgroundColor: "green",
                        padding: "10px 50px",
                        margin: 10,
                        transition: "background-color 0.3s ease",
                        borderRadius: 5,
                        textDecoration: "none"
                      }} > Fight </button>
                    </Link>
                  ) : (
                    <>
                      {deck && elites &&
                        <>
                          <button
                            onClick={redirectZones}
                            style={{
                              color: "#F9DC5C",
                              backgroundColor: "green",
                              padding: "10px 50px",
                              margin: 10,
                              transition: "background-color 0.3s ease",
                              borderRadius: 5,
                              textDecoration: "none"
                            }} > Play </button>
                        </>
                      }
                    </>
                  )
                  }
                  {deck && elites &&
                    <>
                      {
                        player.in_pvp == 'false' &&
                        <button
                          onClick={createPvp}
                          style={{
                            color: "#F9DC5C",
                            backgroundColor: "purple",
                            padding: "10px 50px",
                            margin: 10,
                            transition: "background-color 0.3s ease",
                            borderRadius: 5,
                            textDecoration: "none"
                          }} > PvP </button>
                      }
                      {player.in_pvp == 'wait' &&
                        <button
                          onClick={stopPvp}
                          style={{
                            color: "#F9DC5C",
                            backgroundColor: "purple",
                            padding: "10px 50px",
                            margin: 10,
                            transition: "background-color 0.3s ease",
                            borderRadius: 5,
                            textDecoration: "none"
                          }} >Leave PvP waiting list</button>
                      }
                      {player.in_pvp == 'true' && pvp &&
                        <Link href="/pvp/[id]" as={`/pvp/${pvp.id}`}>
                          <button style={{
                            color: "#F9DC5C",
                            backgroundColor: "purple",
                            padding: "10px 50px",
                            margin: 10,
                            transition: "background-color 0.3s ease",
                            borderRadius: 5,
                            textDecoration: "none"
                          }} > Fight </button>
                        </Link>
                      }
                    </>
                  }
                  {showAlert && <div>
                    <Alert status='warning' width="50%">
                      <AlertIcon />
                      Your Team is not complete!
                    </Alert>
                  </div>
                  }
                </>
              ) :
                <></>
              }
            </div>
          </div>
        ) : (
          <>
            <Auth />
          </>
        )}
      </Layout>
    </>
  )
}
