# Étape de build
FROM node:18-alpine AS build

# Définir le répertoire de travail
WORKDIR /app

# Copier package.json et yarn.lock
COPY package*.json ./
COPY yarn.lock ./

# Installer les dépendances
RUN yarn install

# Copier le reste du code
COPY ./ ./

# Builder l'application Next.js
RUN yarn build

# Étape de production
FROM node:18-alpine AS production

WORKDIR /app

# Copier les fichiers buildés de l'étape précédente
COPY --from=build /app /app

# Exposer le port 3001 pour Next.js
EXPOSE 3001

# Démarrer l'application Next.js
CMD ["yarn", "start"]
